[package]
name = "daemonize"
version = "0.0.1"
authors = ["Fedor Gogolev <knsd@knsd.net>"]
license = "MIT"
homepage = "https://github.com/knsd/daemonize/"
repository = "https://github.com/knsd/daemonize/"
documentation = "https://knsd.github.io/daemonize"

[dependencies]
libc = "0.2.4"
quick-error = "0.1.4"

[dev-dependencies]
log = "0.3.4"
syslog = "3.1.0"
tempdir = "0.3.4"
